version: '3.8'
services:
  db:
    image: postgres:15
    container_name: otp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: otp_db
      POSTGRES_USER: otp_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - otp_db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: otp-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  otp_db_data:
